import { Router } from "express";
import {getAdmins,getAdmin , createAdmin , updateAdmin , deleteAdmin ,loginAdmin } from '../controllers/adminController.js';
const router = Router(); 
router.get('/api/admin', getAdmins); 
router.get('/api/admin/:id', getAdmin); 
router.post('/api/admin', createAdmin);
router.post('/api/loginAdmin', loginAdmin);
router.put('/api/admin/:id', updateAdmin);
router.delete('/api/admin/:id', deleteAdmin);
export default router; 